defaults:
  - optim: adamw
  - scheduler: linear_with_warmup

name: attribute_extraction

dataloader:
  num_workers: 1
  train:
    batch_size: 16
    shuffle: true
  eval:
    batch_size: 16
  
model:
  num_tokens: 512

optim:
  lr: 5e-5

data:
  dataset_dir: ene-20220712_prep
  dev_size: 5
  duplicate_tokens: 64