hydra:
  run:
    dir: outputs 

defaults:
  - train: attribute_extraction

train:
  seed: 1234
  debug_mode: false

  total_updates: 30000
  eval_updates: 1000
  use_checkpoint: false
  checkpoint_updates: 1000
  log_updates: 10

  gradient_accumulation_steps: 1

  data:
    dir: data

  model:
    bert:
      dir: models/roberta_base_wiki201221_janome_bpe_merge_10000_vocab_24000
    epoch: 10

  device:
    fp16: true
    fp16_opt_level: O1
    no_cuda: false
    device: null # Store during execution
    n_gpu: null # Store during execution